In [ ]:
import torch                    # Tensor 데이터의 타입으로 파싱하기 위해 로드 
import torch.nn as nn           # torch안에 nn부분만 로드하여 nn 별칭으로 사용(nn -> 기본 뼈대)
import torch.optim as optim     # 옵티마이저(기울기의 변화를 주는 기능)

In [ ]:
import pandas as pd

In [ ]:
# 데이터셋을 하나 생성 
# 독립, 종속 데이터를 tensor로 생성 
# 독립 변수 -> sklearn을 이용한 ML에서는 2차원 데이터 
x = torch.tensor( [ [1.0], [2.0], [3.0], [4.0] ] )
# 종속 변수 -> sklearn을 이용한 ML에서는 1차원 -> torch에서는 2차원으로 생성 
# 종속 변수는 독립 변수에서 2를 곱하고 1를 더한 값
y = torch.tensor( [ [3.0], [5.0], [7.0], [9.0] ] )

In [ ]:
pd.DataFrame([ [1.0], [2.0], [3.0], [4.0] ])

In [ ]:
type(x)

In [ ]:
# sklearn에서 모델을 생성한다면 -> 가중치가 2이고 절편이 1인 규칙을 찾는 LinearRegression을 이용하여 예측 가능

# torch을 이용한 단순 선형 회귀 
# 순전파 ( 모델 학습 -> 예측 )
    # class 클래스명( 부모클래스 ):  --> 부모클래스의 기능을 상속 받아서 클래스를 선언
class LinearReg(nn.Module):

    # torch의 모듈을 이용한 클래스 생성시 2개의 함수를 필요로 선언 (생성자 함수, forward 함수)

    # 생성자 함수 
    def __init__(self):
        # self : 자기 자신( 클래스를 생성할때 저장이 되는 위치 )
        # super() : 부모 클래스(nn.Module)를 의미
        super(LinearReg, self).__init__()       # 부모 클래스의 생성자 함수를 실행

        # 선형 회귀 모델을 이용
        # nn 모듈 안에 Linear() 모델은 
        # 첫번째 인자값 : 입력 데이터(독립 변수)의 차원(피쳐)의 수 
        # 두번째 인자값 : 출력 데이터의 차원(피쳐)의 수
        self.linear = nn.Linear(1, 1)
    
    def forward(self, x):
        return self.linear(x)


In [ ]:
# 클래스 생성 -> 회귀 모델을 생성
model = LinearReg()

In [ ]:
# 손실 함수 
criterion = nn.MSELoss()

In [ ]:
# 옵티마이저 설정 -> 가중치를 업데이트 
# 어떤 모델의 파라미터를 설정할것인가? -> 첫번째 인자
# lr 매개변수 -> 경사 하강법의 보폭 
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [ ]:
# 순전파 (생성된 모델을 호출하면 -> forward() 함수를 호출하도록 nn.Module에서 설정이 되어있음)
pred = model(x)
# LinearReg 클래스 안에 forward함수를 호출하여 독립변수(x)를 인자값으로 사용한다.

# 손실함수 
loss = criterion(pred, y)

# 기울기를 초기화 
optimizer.zero_grad()

# 역전파 (자동 미분) -> 데이터가 있는 쪽으로 방향을 제시한다 -> 네비게이션
loss.backward()

# 가중치를 업데이트 ( 파라미터(모델) 수정 )
optimizer.step()

# loss 값을 확인 
print(loss)

In [ ]:
# DL 모델은 반복 학습이 기본 설정 -> 학습모드를 평가모드 전환
# eval() : 모델을 평가모드로 전환
# train() : 모델을 학습모드로 전환
model.eval()

# 예측, 평가 ( 메모리의 사용량을 줄이기 위해서 가중치의 계산을 잠시 비활성화  )
with torch.no_grad():
    y_pred = model(x)
    loss = criterion(y_pred, y)
    print(y_pred)
    print(loss)

In [ ]:
# 반복 학습을 통해서 가중치와 편향을 변화 시킨다. 
epochs = 200
model.train()
for epoch in range(epochs):
    # 순전파
    pred = model(x)
    # 손실 함수 
    loss = criterion(pred, y)
    # 기울기 초기화 
    optimizer.zero_grad()
    # 자동 미분(역전파) -> 가중치의 방향을 제시 
    loss.backward()
    # 가중치를 업데이트 
    optimizer.step()

    if (epoch + 1) % 20 == 0:
        # 반복횟수가 20회마다 출력 
        print(f" Epoch : [ {epoch+1}, 200 ], Loss : {round(loss.item(), 6)} ")


In [ ]:
model.eval()

# 예측, 평가 ( 메모리의 사용량을 줄이기 위해서 가중치의 계산을 잠시 비활성화  )
with torch.no_grad():
    y_pred = model(x)
    loss = criterion(y_pred, y)
    print(y_pred)
    print(loss)

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
data = fetch_california_housing()

x = data['data']
y= data['target']

print(x.shape, y.shape)

In [ ]:
import pandas as pd 
# csv 파일을 이용해서 x,y 생성 할때

df = pd.read_csv("../data/california.csv")

# x = df.drop('target', axis=1).values
# y = df['target'].values

In [ ]:
df.head()

In [ ]:
# 1차원 데이터를 2차원으로 변경 
y = y.reshape(-1, 1)

In [ ]:
# 학습, 평가 데이터로 데이터 분할 
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [61]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [68]:
scaler = StandardScaler()
X_train_sc = torch.tensor(scaler.fit_transform(X_train_tensor), dtype=torch.float32)
X_test_sc = torch.tensor(scaler.transform(X_test_tensor), dtype=torch.float32)

In [ ]:
# 선형 회귀 모델 객체를 선언 
class Reg(nn.Module):
    # class  생성할때 입력 데이터의 피쳐의 수를 필수 인자로 설정 
    def __init__(self, _dim):
        super(Reg, self).__init__()
        self.linear = nn.Linear(_dim, 1)
    
    def forward(self, x):
        return self.linear(x)

In [81]:
# 모델을 생성 -> 생성시 입력 데이터의 피쳐의 개수를 
n_feature = X_train.shape[1]
model = Reg(n_feature)

In [82]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [83]:
# 반복 실행하면서 모델에 학습하고 가중치 업데이트 
epochs = 300

for epoch in range(epochs):
    pred = model(X_train_sc)
    loss = criterion(pred, y_train_tensor)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    n = epoch + 1
    # 30회 마다 loss 확인
    if n % 30 == 0:
        print(f"Epoch : [{n} / 500], Loss : {round(loss.item(), 6)}")

Epoch : [30 / 500], Loss : 2.381349
Epoch : [60 / 500], Loss : 1.096873
Epoch : [90 / 500], Loss : 0.714008
Epoch : [120 / 500], Loss : 0.598102
Epoch : [150 / 500], Loss : 0.561633
Epoch : [180 / 500], Loss : 0.54898
Epoch : [210 / 500], Loss : 0.543593
Epoch : [240 / 500], Loss : 0.540528
Epoch : [270 / 500], Loss : 0.538294
Epoch : [300 / 500], Loss : 0.536429


In [84]:
# 학습된 모델을 이용하여 평가 검증 

model.eval()

with torch.no_grad():
    pred = model(X_test_sc)
    loss = criterion(pred, y_test_tensor)

    print(round(loss.item(), 6))

0.559115


In [85]:
for i in range(10):
    print(f"실제 데이터 : {y_test[i]}, 예측 데이터 : {pred[i].item()}")

실제 데이터 : [0.477], 예측 데이터 : 0.8445916175842285
실제 데이터 : [0.458], 예측 데이터 : 1.6717907190322876
실제 데이터 : [5.00001], 예측 데이터 : 2.5393147468566895
실제 데이터 : [2.186], 예측 데이터 : 2.775054454803467
실제 데이터 : [2.78], 예측 데이터 : 2.4001667499542236
실제 데이터 : [1.587], 예측 데이터 : 2.072530746459961
실제 데이터 : [1.982], 예측 데이터 : 2.6747026443481445
실제 데이터 : [1.575], 예측 데이터 : 2.170053243637085
실제 데이터 : [3.4], 예측 데이터 : 2.437168836593628
실제 데이터 : [4.466], 예측 데이터 : 4.015299320220947


In [92]:
model2 = Reg(n_feature)
criterion2 = nn.MSELoss()
optimizer2 = optim.SGD(model2.parameters(), lr = 1e-07)

In [93]:
for epoch in range(300):
    pred2 = model2(X_train_tensor)
    loss2 = criterion2(pred2, y_train_tensor)
    optimizer2.zero_grad()
    loss2.backward()
    optimizer2.step()
    n = epoch+1
    if n %30 == 0:
        print(loss2)

tensor(253.8993, grad_fn=<MseLossBackward0>)
tensor(235.3446, grad_fn=<MseLossBackward0>)
tensor(218.1875, grad_fn=<MseLossBackward0>)
tensor(202.3225, grad_fn=<MseLossBackward0>)
tensor(187.6525, grad_fn=<MseLossBackward0>)
tensor(174.0872, grad_fn=<MseLossBackward0>)
tensor(161.5435, grad_fn=<MseLossBackward0>)
tensor(149.9443, grad_fn=<MseLossBackward0>)
tensor(139.2185, grad_fn=<MseLossBackward0>)
tensor(129.3002, grad_fn=<MseLossBackward0>)


In [96]:
# 비선형 모델 생성 (선형 모델 -> 활성화 함수 -> 선형 모델 )
class Reg2(nn.Module):
    def __init__ (self, _dim):
        super(Reg2, self).__init__()
        # 다중 퍼셉트론 안에 선형 모델 -> 활성화 함수 -> 선형 모델 
        self.model = nn.Sequential(
            # 첫번째 레이어 
            nn.Linear(_dim, _dim), 
            # 활성화 함수 (비선형 구조 파악) ( Relu(일반적으로 사용), Tanh, Sigmoid )
            nn.ReLU(), 
            nn.Linear(_dim, 1)
        )
    def forward(self, x):
        return self.model(x)

In [98]:
model3 = Reg2(n_feature)
criterion3 = nn.MSELoss()
optimizer3 = optim.SGD(model3.parameters(), lr = 0.01)

In [99]:
# 반복 학습 
for epoch in range(300):
    n = epoch + 1

    pred3 = model3(X_train_sc)
    loss3 = criterion3(pred3, y_train_tensor)
    optimizer3.zero_grad()
    loss3.backward()
    optimizer3.step()

    if n % 30 == 0:
        print(f"Epoch[{n} / 300] , Loss : {round(loss3.item(), 6)} ")

Epoch[30 / 300] , Loss : 1.178027 
Epoch[60 / 300] , Loss : 0.704193 
Epoch[90 / 300] , Loss : 0.627344 
Epoch[120 / 300] , Loss : 0.600055 
Epoch[150 / 300] , Loss : 0.584226 
Epoch[180 / 300] , Loss : 0.572908 
Epoch[210 / 300] , Loss : 0.563247 
Epoch[240 / 300] , Loss : 0.554781 
Epoch[270 / 300] , Loss : 0.547175 
Epoch[300 / 300] , Loss : 0.540268 


In [100]:
model3.eval()
with torch.no_grad():           # 버릇처럼 사용 (메모리 최적화)
    pred3 = model3(X_test_sc)
    loss3 = criterion3(pred3, y_test_tensor)

for i in range(10):
    print(f"실제 데이터 : {y_test[i]}, 예측 데이터 : {pred3[i].item()}")

실제 데이터 : [0.477], 예측 데이터 : 0.9546409249305725
실제 데이터 : [0.458], 예측 데이터 : 1.5683015584945679
실제 데이터 : [5.00001], 예측 데이터 : 2.5465738773345947
실제 데이터 : [2.186], 예측 데이터 : 2.7298426628112793
실제 데이터 : [2.78], 예측 데이터 : 2.3614673614501953
실제 데이터 : [1.587], 예측 데이터 : 2.0343313217163086
실제 데이터 : [1.982], 예측 데이터 : 2.691148281097412
실제 데이터 : [1.575], 예측 데이터 : 2.1751351356506348
실제 데이터 : [3.4], 예측 데이터 : 2.4951558113098145
실제 데이터 : [4.466], 예측 데이터 : 4.1764912605285645


In [101]:
# 파이토치 랜덤 고정 
torch.manual_seed(42)

In [103]:
# 딥러닝 분류 모델 
import pandas as pd 
from sklearn.metrics import accuracy_score, classification_report

In [104]:
df = pd.read_csv("../csv/iris.csv")
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [105]:
from sklearn.preprocessing import LabelEncoder

In [106]:
# 선형 모델을 이용하여 분류 -> 로지스틱회귀랑 비슷한 방식 
# 출력의 값이 3개의 피쳐로 출력 (  )
x = df.drop('species', axis=1)
y = df['species']

In [107]:
# y의 값들을 LabelEncoder를 이용하여 숫자로 변환 
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [108]:
# train, test 데이터셋으로 분할 
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

In [109]:
# Sclaer 작업 
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

In [132]:
# Tensor 형태로 변환 
X_train_tensor = torch.tensor(X_train_sc, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_sc, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [133]:
y_test_tensor

tensor([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2, 1, 2,
        2, 1, 1, 0, 2, 0])

In [134]:
# 모델 정의 
class clf(nn.Module):
    def __init__(self, _dim):
        super(clf, self).__init__()
        self.model = nn.Linear(_dim, 3)

    def forward(self, x):
        return self.model(x)

In [135]:
clf_model = clf(x.shape[1])

In [136]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(clf_model.parameters(), lr = 0.01)

In [137]:
# for epoch in range(300):

pred = clf_model(X_train_tensor)
pred

tensor([[-1.0555, -0.0161,  0.2459],
        [ 0.4383,  0.5453,  0.3885],
        [ 1.2105,  0.2381,  0.4830],
        [-0.9651, -0.0235,  0.2334],
        [ 0.6084,  0.1940,  0.4609],
        [ 1.3247,  0.4023,  0.4823],
        [ 0.5160,  0.3219,  0.4121],
        [ 1.0176,  0.4015,  0.4554],
        [ 1.8891,  0.7382,  0.4096],
        [ 1.2489,  1.2650,  0.1908],
        [ 1.9229,  0.6734,  0.4770],
        [ 0.6292,  0.5023,  0.3548],
        [ 0.6718, -0.2366,  0.6202],
        [ 0.5691,  0.1191,  0.4711],
        [ 0.6642,  0.1519,  0.4630],
        [-1.1351,  0.1421,  0.1749],
        [-1.5010,  0.5283, -0.0363],
        [ 1.7048,  0.3070,  0.5873],
        [ 0.9067,  0.7669,  0.3330],
        [-0.9479,  0.2467,  0.1066],
        [ 1.2590,  0.1852,  0.5461],
        [-1.4900,  0.4796, -0.0109],
        [ 1.2691,  1.1066,  0.2167],
        [-0.7832, -0.0544,  0.2650],
        [ 0.6049, -0.0480,  0.5269],
        [ 1.0649,  0.6524,  0.4047],
        [ 1.2542,  0.5346,  0.4411],
 

In [138]:
torch.max(pred, 1)

torch.return_types.max(
values=tensor([0.2459, 0.5453, 1.2105, 0.2334, 0.6084, 1.3247, 0.5160, 1.0176, 1.8891,
        1.2650, 1.9229, 0.6292, 0.6718, 0.5691, 0.6642, 0.1749, 0.5283, 1.7048,
        0.9067, 0.2467, 1.2590, 0.4796, 1.2691, 0.2650, 0.6049, 1.0649, 1.2542,
        0.3286, 0.7944, 0.3314, 0.5124, 0.6467, 0.5990, 0.8803, 1.1873, 1.2748,
        0.4787, 0.4393, 1.2283, 0.9021, 0.3442, 0.9160, 0.5837, 1.8737, 0.2433,
        0.3164, 0.8869, 0.1639, 0.4388, 0.2546, 0.2189, 0.4337, 1.3192, 0.5406,
        0.2632, 0.7770, 0.4529, 1.3174, 0.1531, 0.8869, 0.1812, 0.7986, 1.0122,
        0.2743, 0.9618, 0.5901, 2.1779, 0.6490, 1.0158, 1.0932, 0.1984, 0.2977,
        0.3518, 1.4044, 0.5471, 1.4771, 0.6378, 1.1526, 1.1017, 0.9014, 0.2156,
        0.9772, 1.4027, 0.5042, 1.1799, 0.6101, 1.3566, 0.3942, 0.8603, 0.2167,
        0.6713, 0.9054, 0.5992, 0.1991, 1.0156, 2.4448, 1.2504, 1.3177, 0.9307,
        0.6014, 1.1698, 0.4408, 1.3526, 1.4998, 0.3672, 0.7791, 0.7892, 0.4568,
        0

In [139]:
# 반복 학습 
clf_model.train()
for epoch in range(300):
    pred = clf_model(X_train_tensor)
    loss = criterion(pred, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    n = epoch + 1
    if n % 30 == 0:
        print(f"Epoch : [{n} / 300] , Loss : {round(loss.item(), 6)}")

Epoch : [30 / 300] , Loss : 1.285558
Epoch : [60 / 300] , Loss : 1.008317
Epoch : [90 / 300] , Loss : 0.839348
Epoch : [120 / 300] , Loss : 0.733256
Epoch : [150 / 300] , Loss : 0.6624
Epoch : [180 / 300] , Loss : 0.611932
Epoch : [210 / 300] , Loss : 0.573967
Epoch : [240 / 300] , Loss : 0.544145
Epoch : [270 / 300] , Loss : 0.519919
Epoch : [300 / 300] , Loss : 0.499716


In [140]:
# 평가 
clf_model.eval()

with torch.no_grad():
    pred = clf_model(X_test_tensor)
    _, pred_idx = torch.max(pred, 1)

acc = accuracy_score( y_test, pred_idx )
print("정확도 : ", round(acc, 4))
print(classification_report( y_test, pred_idx ))

정확도 :  0.8
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.40      0.57        10
           2       0.62      1.00      0.77        10

    accuracy                           0.80        30
   macro avg       0.88      0.80      0.78        30
weighted avg       0.88      0.80      0.78        30

