In [1]:
import torch 
import torch.nn.functional as F

In [ ]:
# 임의의 문장 임베딩 데이터 
# 3개의 단어에 각 단어는 4개의 차원의 숫자로 표현
x = torch.randn(3, 4)
x

tensor([[ 1.1933, -1.4900, -0.5070,  0.1790],
        [ 0.0775,  0.1155, -0.6432, -2.4255],
        [-0.5108, -0.0621, -1.6623,  1.0867]])

In [ ]:
# Query, Key, Value의 임의의 가중치 행렬로 생성 ( 원래는 학습이 되는 가중치 행렬 부분 )
w_q = torch.randn(4, 4)
w_k = torch.randn(4, 4)
w_v = torch.randn(4, 4)

In [4]:
# x의 데이터와 각각의 가중치 행렬을 곱하여 q, k, v를 생성 
q = torch.matmul(x, w_q)
k = torch.matmul(x, w_k)
v = torch.matmul(x, w_v)

In [5]:
# Attention Score를 생성  -> Query와 Key의 내적
attention_score = torch.matmul( q, k.T )

In [7]:
# Attention_score는 고차원일수록 발산를 하기 때문에 Key 차원의 수의 루트의 씌워서 나눠준다. 
d_k = k.size(1)

In [8]:
# 스케일링과 스프크맥스를 통해서 확률로 변환 (모든 행의 합이 1)
attention_weight = F.softmax( attention_score / (d_k ** 0.5), dim=1 )
attention_weight

tensor([[4.8268e-01, 6.7700e-04, 5.1665e-01],
        [1.4843e-01, 9.1547e-12, 8.5157e-01],
        [1.4216e-02, 9.8578e-01, 4.5336e-07]])

In [9]:
output = torch.matmul(attention_weight, v)
output

tensor([[-0.0900,  1.6335,  0.1672, -0.8859],
        [ 1.2838,  3.4769,  0.9456, -1.8613],
        [-0.0231, -2.2437,  4.7036, -0.3540]])